version: '3'

networks:
  app_network:
    driver: bridge

services:
  homelib-api:
    image: homelib_service
    build: .
    depends_on:
      - homelib_db
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/app/src
      - /usr/app/src/node_modules
    networks:
      - app_network
    restart: always
    environment:
      - PORT=${PORT}
    command: npm run start:dev

  homelib_db:
    image: homelib_db
    build: ./postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:
